services:
  main_db:
    image: postgres:latest
    container_name: chemdb
    environment:
      TZ: America/Lima
      POSTGRES_USER: maximus
      POSTGRES_PASSWORD: MaximusTheGreat50
      POSTGRES_DB: chemdb
    ports:
      - "5435:5432"
    volumes:
      #- /home/cisco/postgres-data:/var/lib/postgresql/data
      - ./init_chemdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - unrd_subway
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maximus -d chemdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

networks:
  unrd_subway:
    driver: bridge

volumes:
  postgres-data: # for this give the permissions(sudo chown -R 1000:1000 ./es-data,sudo chmod -R 755 ./es-data)
    driver: local
