server.port=8081
spring.application.name=chemxr_api

spring.r2dbc.url=r2dbc:postgresql://localhost:5435/chemdb
spring.r2dbc.username=maximus
spring.r2dbc.password=MaximusTheGreat50
spring.r2dbc.pool.enabled=true
