spring.application.name=chemxr_api

# PostgreSQL (R2DBC)
spring.r2dbc.url=r2dbc:postgresql://localhost:5435/chemdb
spring.r2dbc.username=maximus
spring.r2dbc.password=MaximusTheGreat50
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10
